#!/usr/bin/env python
"""run_inventory.py — batch assessment over the package inventory (Phase A).

Reads config/inventory.json (generated by tools/build_inventory.py), decides
which packages are stale, and runs the assessment pipeline for each stale
package in parallel (ThreadPoolExecutor, same pattern as
tests/regression/run_regression.py). Batch runs go through the CLI/pipeline
only — never through the HTTP server (single-threaded).

Staleness (a stale package gets (re-)assessed):
  - never assessed: no assessment record for the name in
    <data-dir>/audit/assessments.jsonl
  - version-mismatch: newest assessment's version != inventory version
  - config-changed: newest assessment's config_sha256 != the current
    decision_rules.yml sha256
  - version-unresolved: inventory version is null (not in the snapshot
    index) — currency cannot be determined
--all forces re-assessment of every package.

--offline replays decisions from the regression cache
(tests/regression/cache/<name>.json, committed public-CRAN data) instead of
running the pipeline — no network, no R, no audit writes; results are marked
mode=offline-replay. For tests/dry-runs only.

Per-package failures never abort the batch: the exception is captured into
the package's result row and the run continues.

Writes <data-dir>/inventory_runs/<UTC-ts>/summary.json.

Usage:
  python run_inventory.py [--all] [--jobs N] [--data-dir DIR] [--offline]
                          [--limit N] [--tier TIER] [--inventory PATH]
                          [--cache-dir DIR]
stdlib only. Run from the repo root.
"""

from __future__ import annotations

import argparse
import json
import sys
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parent
sys.path.insert(0, str(REPO))

from gateway import decision as decision_mod  # noqa: E402
from gateway import pipeline  # noqa: E402

DEFAULT_INVENTORY = REPO / "config" / "inventory.json"
DEFAULT_DATA_DIR = REPO / "data"
DEFAULT_CACHE_DIR = REPO / "tests" / "regression" / "cache"
DEFAULT_TIER = "gxp-support"


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def load_inventory(path: Path) -> dict:
    return json.loads(Path(path).read_text(encoding="utf-8"))


def latest_assessments(data_dir: Path) -> dict[str, dict]:
    """Newest assessment record per package name from the audit log
    (the log is append-only, so the last occurrence wins)."""
    path = Path(data_dir) / "audit" / "assessments.jsonl"
    latest: dict[str, dict] = {}
    if not path.is_file():
        return latest
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
            except json.JSONDecodeError:
                continue
            if rec.get("record_type") == "assessment" and rec.get("package"):
                latest[rec["package"]] = rec
    return latest


def staleness(entry: dict, record: dict | None,
              current_config_sha256: str) -> tuple[bool, str]:
    """(is_stale, reason) for one inventory entry against its newest
    assessment record (or None) and the current ruleset identity."""
    if record is None:
        return True, "never-assessed"
    if entry.get("version") is None:
        return True, "version-unresolved"
    if record.get("version") != entry["version"]:
        return True, "version-mismatch"
    if record.get("config_sha256") != current_config_sha256:
        return True, "config-changed"
    return False, "current"


def assess_package(entry: dict, tier: str, data_dir: Path,
                   offline: bool, cache_dir: Path,
                   actor: str = "cli") -> dict:
    """One package: full pipeline, or offline replay from the regression
    cache. Returns the summary row; raises on failure (caller captures)."""
    name = entry["name"]
    row = {"name": name, "version": entry.get("version"),
           "status": "assessed", "decision": None, "overall_score": None,
           "run_id": None}
    if offline:
        cache = Path(cache_dir) / f"{name}.json"
        if not cache.is_file():
            raise RuntimeError(
                f"no regression cache for {name} — offline mode replays "
                "fixture packages only")
        c = json.loads(cache.read_text(encoding="utf-8"))
        ruleset = decision_mod.RuleSet.load(decision_mod.DEFAULT_CONFIG)
        dec = decision_mod.decide((c.get("score") or {}).get("overall_score"),
                                  c.get("tier") or tier, c["evidence"],
                                  ruleset)
        row.update({"decision": dec["decision"],
                    "overall_score": dec["overall_score"],
                    "version": c.get("version", row["version"]),
                    "mode": "offline-replay"})
        return row

    spec = {"package": name, "version": entry.get("version")}
    a = pipeline.run_assessment(spec, tier, data_dir=Path(data_dir),
                                actor=actor)
    row.update({"decision": a["decision"]["decision"],
                "overall_score": a["decision"]["overall_score"],
                "version": a["ingest"]["version"],
                "run_id": Path(a["run_dir"]).name,
                "mode": "pipeline"})
    return row


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="batch assessment over the "
                                 "package inventory")
    ap.add_argument("--all", action="store_true",
                    help="re-assess every package, ignoring staleness")
    ap.add_argument("--jobs", type=int, default=3)
    ap.add_argument("--data-dir", default=str(DEFAULT_DATA_DIR))
    ap.add_argument("--offline", action="store_true",
                    help="replay decisions from the regression cache "
                         "(no network, no R, no audit writes)")
    ap.add_argument("--limit", type=int, default=None,
                    help="assess at most N stale packages (testing)")
    ap.add_argument("--tier", default=DEFAULT_TIER,
                    help="intended-use tier for assessments "
                         f"(default {DEFAULT_TIER})")
    ap.add_argument("--inventory", default=str(DEFAULT_INVENTORY))
    ap.add_argument("--cache-dir", default=str(DEFAULT_CACHE_DIR))
    ap.add_argument("--actor", default="cli",
                    help="actor id recorded on audit records "
                         "(default: cli)")
    args = ap.parse_args(argv)

    inventory = load_inventory(Path(args.inventory))
    entries = inventory.get("packages", [])
    data_dir = Path(args.data_dir)
    ruleset = decision_mod.RuleSet.load(decision_mod.DEFAULT_CONFIG)

    assessed = latest_assessments(data_dir)
    plan = []
    skipped = []
    for entry in entries:
        stale, reason = (True, "forced") if args.all else staleness(
            entry, assessed.get(entry["name"]), ruleset.sha256)
        if stale:
            plan.append({**entry, "stale_reason": reason})
        else:
            skipped.append({"name": entry["name"],
                            "version": entry.get("version"),
                            "status": "skipped-current",
                            "decision": assessed[entry["name"]].get("decision"),
                            "overall_score":
                                assessed[entry["name"]].get("overall_score"),
                            "run_id": None})
    if args.limit is not None:
        plan = plan[:args.limit]

    print(f"[inventory-run] {len(entries)} packages, {len(plan)} stale "
          f"({len(skipped)} current), tier={args.tier}, mode="
          f"{'offline' if args.offline else 'pipeline'}, jobs={args.jobs}")

    results: list[dict] = list(skipped)
    failures = 0

    def _run(entry):
        try:
            row = assess_package(entry, args.tier, data_dir,
                                 args.offline, Path(args.cache_dir),
                                 actor=args.actor)
            row["stale_reason"] = entry.get("stale_reason")
            return row
        except Exception as e:  # noqa: BLE001 — captured, batch continues
            return {"name": entry["name"], "version": entry.get("version"),
                    "status": "failed", "decision": None,
                    "overall_score": None, "run_id": None,
                    "error": f"{type(e).__name__}: {e}",
                    "stale_reason": entry.get("stale_reason")}

    if args.jobs <= 1 or len(plan) <= 1:
        for entry in plan:
            results.append(_run(entry))
    else:
        with ThreadPoolExecutor(max_workers=args.jobs) as ex:
            for row in ex.map(_run, plan):
                results.append(row)

    for row in results:
        if row["status"] == "failed":
            failures += 1
        mark = {"assessed": "ASSESSED", "skipped-current": "current",
                "failed": "FAILED"}[row["status"]]
        s = (f"{row['overall_score']:.4f}"
             if row.get("overall_score") is not None else "None")
        print(f"[inventory-run] {row['name']:<24} {str(row.get('version')):<10} "
              f"{s:>7}  {str(row.get('decision')):<19} {mark}"
              + (f"  ({row['error']})" if row["status"] == "failed" else ""))

    stamp = _now().replace(":", "")
    run_dir = data_dir / "inventory_runs" / stamp
    run_dir.mkdir(parents=True, exist_ok=True)
    summary = {
        "schema": "rval-gateway inventory run v1",
        "started_at": stamp,
        "inventory": str(Path(args.inventory)),
        "snapshot": inventory.get("snapshot"),
        "tier": args.tier,
        "mode": "offline" if args.offline else "pipeline",
        "config_version": ruleset.version,
        "config_sha256": ruleset.sha256,
        "totals": {
            "packages": len(entries),
            "stale": len(plan),
            "assessed": sum(1 for r in results if r["status"] == "assessed"),
            "skipped-current": len(skipped),
            "failed": failures,
        },
        "results": sorted(results, key=lambda r: r["name"].lower()),
    }
    (run_dir / "summary.json").write_text(
        json.dumps(summary, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8")
    print(f"[inventory-run] {summary['totals']['assessed']} assessed, "
          f"{len(skipped)} current, {failures} failed -> "
          f"{run_dir / 'summary.json'}")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
